[package]
name = "director-studio"
version = "0.1.0"
description = "人人都是电影导演"
authors = ["Director Studio"]
edition = "2021"

[lib]
name = "director_studio_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
